### ISSUE TITLE
Using phystrix in unbuntu14

### ISSUE THREAD

**Issue by ankahla** [upwork/phystrix#18]
Hi,
I tried this awesome bundle in my backend application with rabbitmq, to avoid requesting the database when it is down (Mysql server has gone away) but for me once I have a problem with a database I got always the phystrix fallback() function executed even if the database return back online and phystrix never execute the run method. 
I heared that the problem may be caused by no support of APC cache in ubuntu14, but I thing it is not the problem because the function apc_add() work fine.
I thing that the function run() is executed if the value in cache is expired but in my case the database is always considered offline.

**Comment by lcf** [comment]
Hi @ankahla,

One of APC limitations is that values never expire within a single request, want to make sure that's not your case

**Comment by ankahla** [comment]
Thank you for your response 
In fact I am using rabbitmq as a daemon (always running and listning to new messages), I don't know if it is an answer to the question.

**Comment by antiphp** [comment]
@ankahla: I ran into same problem when the fallback throws an exception, which in my case was desired behaviour.

**Comment by lcf** [comment]
could you please provide more details on your set up with rabbitmq and re-open if still relevant
