### ISSUE TITLE
Short circuit happening earlier than threshold 

### ISSUE THREAD

**Issue by skaushikWebuy** [upwork/phystrix#28]
hi 
below are my phystrix settings

'errorThresholdPercentage' => 50,
'requestVolumeThreshold' => 10,
'sleepWindowInMilliseconds' => 10000,
'rollingStatisticalWindowInMilliseconds' => 20000,

My query is that the circuit breaker short circuits the request when I have 2nd consecutive failing request rather than reaching the threshold request above 10.

What I mean to say is if I have initially 2 failing request comes, then the circuit breaker gets short circuited on the 2nd request before reaching the threshold of requests i.e. 10

Can you provide help how to make it accurate.

**Comment by lcf** [comment]
I wasn't able to reproduce. Are those under 'circuitBreaker' section of the configuration @skaushikWebuy ? Is there a way I could reproduce the issue?

**Comment by skaushikWebuy** [comment]
Yes

**Comment by lcf** [comment]
@skaushikWebuy if this is still relevant, could you provide a code sample to reproduce and re-open
