### ISSUE TITLE
Using phystrix to protect access to repository / How to prevent regular exceptions from triggering the circuit

### ISSUE THREAD

**Issue by bicatu** [upwork/phystrix#34]
Hi, I am considering using Phystrix in my projects and one item that seems a potential problem is when using, for example, to protect Repositories.

Imagine I am using Doctrine and I try to insert something and the server is fine but the data is problematic (would violate a unique restriction). The error would be exposed as an Exception and, if my understanding is correct, it would cause it to be considered a failure inside the execute method.

Right now my Repository methods catch the Doctrine Exceptions and re-throw them with a more domain specific but are still exceptions.

Am I correct on my assumption and if so, any suggestion on how to protect external services that expose their errors as Exceptions as well?

**Comment by lcf** [comment]
Hi @bicatu , thank you for the question!

There is a special kind of exception, specifically for the types of errors you describe, [BadRequestException](https://github.com/upwork/phystrix/blob/master/library/Odesk/Phystrix/Exception/BadRequestException.php#L22)

> This exception is treated differently and allows to propagate without any stats tracking or fallback logic

This would be a good idea to reflect this in the README.

**Comment by bicatu** [comment]
Thank you. Indeed it would be nice if it could be mentioned at the documentation. PR?

**Comment by lcf** [comment]
@bicatu sure, all PRs are welcome!

**Comment by omar-faruk-sust** [comment]
hi @bicatu,

Did you find any way to handle your Doctrine Exceptions instead of re-throwing them? I am also facing similar issue. It would be nice if you share how you handle in your case.

Thanks
