### ISSUE TITLE
if the caller try frequently, the openCircuits will never expire

### ISSUE THREAD

**Issue by xiazemin** [upwork/phystrix#41]
phystrix/library/Odesk/Phystrix/ArrayStateStorage.php +112

            $allow = $this->openCircuits[$commandKey] < $this->getTimeInMilliseconds();
            $this->openCircuits[$commandKey] = $this->getTimeInMilliseconds() + $sleepingWindowInMilliseconds;
            return $allow;

 should like this
             $allow = $this->openCircuits[$commandKey] < $this->getTimeInMilliseconds();
            if($allow){
                $this->openCircuits[$commandKey] = $this->getTimeInMilliseconds() + $sleepingWindowInMilliseconds;
            }
            return $allow;

**Comment by lcf** [comment]
this storage is to be used only for testing and development, that said you are absolutely right @xiazemin in your observation!
if you care to submit a PR I will gladly accept it

**Comment by lcf** [comment]
thank you!
